version: 2
project_name: app-dev-clean

before:
  hooks:
    - go mod tidy

builds:
  - id: app-dev-clean
    main: .
    binary: app-dev-clean
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

brews:
  - repository:
      owner: latif-essam
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/latif-essam/app-dev-clean"
    description: "Cross-platform dev-cache cleaner (RN/Expo/Flutter/native)"
    license: "MIT"
    install: |
      bin.install "app-dev-clean"
      bin.install_symlink "app-dev-clean" => "adc"

scoops:
  - repository:
      owner: latif-essam
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/latif-essam/app-dev-clean"
    description: "Cross-platform dev-cache cleaner (RN/Expo/Flutter/native)"
    license: "MIT"

release:
  github:
    owner: latif-essam
    name: app-dev-clean
